### ISSUE TITLE
reduce precision of filedates in existing checkpoints

### ISSUE THREAD

**Issue by benjamin-von-der-weiden** [leo-bogert/checkpoint#3]
to make them compatible afterwards with mac-os' or other non-precise filedates in checkpoint.txt

**Comment by leo-bogert** [comment]
Please clarify if this is satisfied by removing the decimals upon the seconds, i.e. always specifying times as "HH:MM:SS", or if you have a filesystem which is even less precise than seconds?

**Comment by benjamin-von-der-weiden** [comment]
HFS Plus has the resolution of one second. I'm not aware of any other filesystem except some FAT flavours which have a resolution less precise than seconds.

**Comment by leo-bogert** [comment]
> HFS Plus has the resolution of one second. I'm not aware of any other filesystem except some FAT flavours which have a resolution less precise than seconds.

Thanks.
Then I would say that:
- Windows and thus FAT is out of our scope of development.
- the 1 second resolution it uses now is fine for all other filesystems.
- so we can keep it at "HH:MM:SS" with full seconds accuracy for simplicity of the codebase until real usage of Checkpoint reveals that trimming the accuracy will be needed.

The Java and Python versions will always do "HH:MM:SS" already, and if you have existing checkpoints which you need to remove the milliseconds from I suspect you can use the `--rewrite-only` option of the Python script to accomplish that: It was previously using milliseconds so the code to parse them is still existing probably, but the code for writing the file to disk will remove the milliseconds without any additional option being required.  
(Using the "rewrite" command of the Java version won't work because it never supported anything beyond seconds so it has no code to parse milliseconds.)

Thus closing this for now, if rewriting doesn't work as desired or it turns out you do need the ability to reduce the resolution beyond seconds then feel free to ask me to re-open it.
