### ISSUE TITLE
new option --exclude-times abcm

### ISSUE THREAD

**Issue by benjamin-von-der-weiden** [leo-bogert/checkpoint#4]
to have an option to verify file integrity where filedates are screwed or not an issue

**Comment by leo-bogert** [comment]
Fixed by 12a864f85fe1819348b8cf83ddaea78ab1e053c9 for the Python implementation.  
The Java implementation will also implement this eventually, meanwhile the Python one can be used to postprocess the output of the Java implementation to accomplish this.  
The README of the Java version will explain this in detail.
