### ISSUE TITLE
backport new features

### ISSUE THREAD

**Issue by benjamin-von-der-weiden** [leo-bogert/checkpoint#7]
to older bash and python versions once a java version is available

**Comment by leo-bogert** [comment]
Is this critically important to you or just something nice to have?
Notice that Java seems to be available for basically any popular operating system, especially considering the open source OpenJDK version of it - which I also use for development and is mostly equal to the proprietary Oracle one.
So are you sure there is an OS you couldn't use it on?

I'm most proficient with Java, so long-term I would like to keep the non-Java versions limited to the basic feature of creating checkpoints, and deal with everything else in the Java version.

This would allow me to keep testing the Java version against the other implementations on Travis CI, while keeping the maintenance effort very low, and avoiding that the other implementations have bugs because I don't work with Bash/Python as often.

**Comment by benjamin-von-der-weiden** [comment]
I did have the fetish of not installing 3rd party software on macOS if there is a workaround to do this with software the operating system ships with, because there is no serious systemwide package manager like I'm used to work with on any linux distribution ever since. However, i gave that up as macOS can be considered legacy tech wise in so many aspects. I will just go ahead installing Java and maintain it on my own.

**Comment by leo-bogert** [comment]
> I did have the fetish of not installing 3rd party software on macOS if there is a workaround to do this with software the operating system ships with, because there is no serious systemwide package manager like I'm used to work with on any linux distribution ever since. However, i gave that up as macOS can be considered legacy tech wise in so many aspects. I will just go ahead installing Java and maintain it on my own.

Heh well there currently ain't no cross-platform programming language which will not have you end up with one of these:
- the runtime environment of the language being installed on the OS and having to update it there.
- or the runtime environment compiled into the binary of the specific piece of software so you don't have to install it. This **would** be possible for Java with GraalVM nowadays. However then it only appears like nothing has to be updated, but in fact the code of the language runtime which was compiled in the binary will grow outdated then as well. So instead of updating Java you then would have to constantly recompile against new GraalVM versions.

Matter of fact is: Any decent software will use libraries to not constantly re-invent the wheel, and the libraries have to be updated once in a while. Java is just another one.  
So I suppose from your "legacy software" statement we both agree that it's MacOS fault that they can't bother to provide a package manager, not mine as a developer of software which could benefit from one like any other software which is not trivial enough to not need any libs :)  
It's pretty insane that they didn't fix this yet, and I probably should not spend my time in workarounds for it like maintaining the Python/Bash versions.

So let's close this now.

If you're interested in GraalVM binaries for e.g. using Checkpoint off an USB stick without having to install Java on a machine then I or you could try tinkering with GraalVM some day. However I haven't worked with it yet so I'd rather not get distracted with it for now.  
I do suspect that it will be trivial to get this working yourself:  
The Java rewrite uses Gradle to compile it, which is a state-of-the-art build system - IIRC it was written by Google for Android.  
It abstracts the compiler so much that the Gradle script doesn't even contain the name of the compiler. As a result the build script is only a handful of lines (build.gradle is the filename). So I would suspect that GraalVM may be capable of eating a Gradle build script without much hassle, or that Gradle can easily be configured to use GraalVM.  
So if you need this you may then google for "gradle java graalvm" and if you get it working hand me the required changes for merging into the repository.
